// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Cargar .env del proyecto y priorizarlo sobre DATABASE_URL heredado del sistema
// (sin override, dotenv no pisa variables ya definidas → a veces queda localhost:5432).
dotenv.config({ path: path.resolve(process.cwd(), ".env"), override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
